version: '3'

networks:
  reindexr: ~

services:
  php:
    build:
      context: .
    networks:
      - reindexr
    volumes:
      - .:/app
  
  elasticsearch:
    image: elasticsearch:6.8.16
    # for ARM use the following image. Elasticsearch docker container support arm natively from 7.x+
#    image: elyalvarado/elasticsearch-arm64:6.8.16
    networks:
      - reindexr
    environment:
      - "discovery.type=single-node"
      - "xpack.ml.enabled=false"
    ports:
      - "9200:9200"
