version: '3'

networks:
  reindexr: ~

services:
  php:
    build:
      context: .
    networks:
      - reindexr
  
  elasticsearch:
    image: elasticsearch:6.8.16
    networks:
      - reindexr
    environment:
      - "discovery.type=single-node"
      - "xpack.ml.enabled=false"
    ports:
      - "9200:9200"
